spring.application.name=nova-backend


spring.datasource.url=jdbc:postgresql://ep-cold-morning-agc9fz07-pooler.c-2.eu-central-1.aws.neon.tech/Gestione_Ordini?user=neondb_owner&password=npg_eQ4FyKrsiL8u&sslmode=require&channelBinding=require

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
